<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class PendaftarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create dummy CV files
        Storage::disk('public')->makeDirectory('cv');
        
        $pendaftars = [
            [
                'id' => 1,
                'id_lowongan' => 5,
                'name' => 'John Doe',
                'gender' => 'male',
                'dob' => '2000-11-02',
                'address' => 'Jl. Raya Sidoarjo No. 123, Sidoarjo, Jawa Timur',
                'no_telp' => '08785555682',
                'university' => 'Universitas Brawijaya',
                'major' => 'Teknik Informatika',
                'ipk' => 3.88,
                'status' => 'accepted',
                'path_cv' => 'cv/john_doe_cv.pdf',
            ],
            [
                'id' => 2,
                'id_lowongan' => 3,
                'name' => 'Jane Smith',
                'gender' => 'female',
                'dob' => '2001-05-15',
                'address' => 'Jl. Merdeka No. 45, Surabaya, Jawa Timur',
                'no_telp' => '08123456789',
                'university' => 'Institut Teknologi Sepuluh Nopember',
                'major' => 'Sistem Informasi',
                'ipk' => 3.75,
                'status' => 'accepted',
                'path_cv' => 'cv/jane_smith_cv.pdf',
            ],
            [
                'id' => 3,
                'id_lowongan' => 1,
                'name' => 'Ahmad Zulkifli',
                'gender' => 'male',
                'dob' => '2000-08-22',
                'address' => 'Jl. Diponegoro No. 78, Malang, Jawa Timur',
                'no_telp' => '08567891234',
                'university' => 'Universitas Airlangga',
                'major' => 'Akuntansi',
                'ipk' => 3.65,
                'status' => 'rejected',
                'path_cv' => 'cv/ahmad_zulkifli_cv.pdf',
            ],
            [
                'id' => 4,
                'id_lowongan' => 7,
                'name' => 'Siti Nurhaliza',
                'gender' => 'female',
                'dob' => '2001-03-10',
                'address' => 'Jl. Pahlawan No. 56, Gresik, Jawa Timur',
                'no_telp' => '08234567890',
                'university' => 'Universitas Negeri Surabaya',
                'major' => 'Manajemen Bisnis',
                'ipk' => 3.92,
                'status' => 'accepted',
                'path_cv' => 'cv/siti_nurhaliza_cv.pdf',
            ],
            [
                'id' => 5,
                'id_lowongan' => 2,
                'name' => 'Budi Santoso',
                'gender' => 'male',
                'dob' => '2000-12-30',
                'address' => 'Jl. Gatot Subroto No. 90, Mojokerto, Jawa Timur',
                'no_telp' => '08998765432',
                'university' => 'Universitas Brawijaya',
                'major' => 'Manajemen',
                'ipk' => 3.55,
                'status' => 'pending',
                'path_cv' => 'cv/budi_santoso_cv.pdf',
            ],
            [
                'id' => 6,
                'id_lowongan' => 1,
                'name' => 'Dewi Lestari',
                'gender' => 'female',
                'dob' => '2001-07-18',
                'address' => 'Jl. Pemuda No. 33, Surabaya, Jawa Timur',
                'no_telp' => '08512345678',
                'university' => 'Universitas Airlangga',
                'major' => 'Akuntansi',
                'ipk' => 3.70,
                'status' => 'accepted',
                'path_cv' => 'cv/dewi_lestari_cv.pdf',
            ],
            [
                'id' => 7,
                'id_lowongan' => 1,
                'name' => 'Rudi Hartono',
                'gender' => 'male',
                'dob' => '2000-09-25',
                'address' => 'Jl. Basuki Rahmat No. 88, Sidoarjo, Jawa Timur',
                'no_telp' => '08765432109',
                'university' => 'Universitas Brawijaya',
                'major' => 'Akuntansi',
                'ipk' => 3.50,
                'status' => 'accepted',
                'path_cv' => 'cv/rudi_hartono_cv.pdf',
            ],
            [
                'id' => 8,
                'id_lowongan' => 2,
                'name' => 'Lina Marlina',
                'gender' => 'female',
                'dob' => '2001-04-12',
                'address' => 'Jl. Ahmad Yani No. 77, Malang, Jawa Timur',
                'no_telp' => '08234567891',
                'university' => 'Institut Teknologi Sepuluh Nopember',
                'major' => 'Manajemen',
                'ipk' => 3.80,
                'status' => 'accepted',
                'path_cv' => 'cv/lina_marlina_cv.pdf',
            ],
            [
                'id' => 9,
                'id_lowongan' => 2,
                'name' => 'Agus Setiawan',
                'gender' => 'male',
                'dob' => '2000-06-08',
                'address' => 'Jl. Veteran No. 55, Gresik, Jawa Timur',
                'no_telp' => '08987654321',
                'university' => 'Universitas Negeri Surabaya',
                'major' => 'Ekonomi',
                'ipk' => 3.45,
                'status' => 'rejected',
                'path_cv' => 'cv/agus_setiawan_cv.pdf',
            ],
            [
                'id' => 10,
                'id_lowongan' => 3,
                'name' => 'Fitri Handayani',
                'gender' => 'female',
                'dob' => '2001-01-20',
                'address' => 'Jl. Sudirman No. 99, Surabaya, Jawa Timur',
                'no_telp' => '08123456780',
                'university' => 'Institut Teknologi Sepuluh Nopember',
                'major' => 'Teknik Informatika',
                'ipk' => 3.85,
                'status' => 'accepted',
                'path_cv' => 'cv/fitri_handayani_cv.pdf',
            ],
            [
                'id' => 11,
                'id_lowongan' => 5,
                'name' => 'Eko Prasetyo',
                'gender' => 'male',
                'dob' => '2000-11-30',
                'address' => 'Jl. Kertajaya No. 44, Surabaya, Jawa Timur',
                'no_telp' => '08567890123',
                'university' => 'Universitas Brawijaya',
                'major' => 'Psikologi',
                'ipk' => 3.60,
                'status' => 'accepted',
                'path_cv' => 'cv/eko_prasetyo_cv.pdf',
            ],
            [
                'id' => 12,
                'id_lowongan' => 5,
                'name' => 'Maya Sari',
                'gender' => 'female',
                'dob' => '2001-02-14',
                'address' => 'Jl. Raya Darmo No. 66, Surabaya, Jawa Timur',
                'no_telp' => '08234567892',
                'university' => 'Universitas Airlangga',
                'major' => 'Manajemen SDM',
                'ipk' => 3.75,
                'status' => 'pending',
                'path_cv' => 'cv/maya_sari_cv.pdf',
            ],
            [
                'id' => 13,
                'id_lowongan' => 7,
                'name' => 'Hendra Wijaya',
                'gender' => 'male',
                'dob' => '2000-08-05',
                'address' => 'Jl. Raya Gubeng No. 22, Surabaya, Jawa Timur',
                'no_telp' => '08987654322',
                'university' => 'Universitas Negeri Surabaya',
                'major' => 'Komunikasi',
                'ipk' => 3.55,
                'status' => 'accepted',
                'path_cv' => 'cv/hendra_wijaya_cv.pdf',
            ],
            [
                'id' => 14,
                'id_lowongan' => 7,
                'name' => 'Rina Susanti',
                'gender' => 'female',
                'dob' => '2001-05-28',
                'address' => 'Jl. Raya Lontar No. 11, Surabaya, Jawa Timur',
                'no_telp' => '08123456781',
                'university' => 'Universitas Brawijaya',
                'major' => 'Manajemen Pemasaran',
                'ipk' => 3.68,
                'status' => 'rejected',
                'path_cv' => 'cv/rina_susanti_cv.pdf',
            ],
            [
                'id' => 15,
                'id_lowongan' => 1,
                'name' => 'Bambang Sutrisno',
                'gender' => 'male',
                'dob' => '2000-10-15',
                'address' => 'Jl. Ngagel No. 77, Surabaya, Jawa Timur',
                'no_telp' => '08567890124',
                'university' => 'Universitas Airlangga',
                'major' => 'Akuntansi',
                'ipk' => 3.72,
                'status' => 'accepted',
                'path_cv' => 'cv/bambang_sutrisno_cv.pdf',
            ],
        ];

        foreach ($pendaftars as $pendaftar) {
            // Create dummy CV file
            Storage::disk('public')->put($pendaftar['path_cv'], 'Dummy CV content for ' . $pendaftar['name']);
            
            DB::table('transaksi_pendaftar')->insert([
                'id' => $pendaftar['id'],
                'id_lowongan' => $pendaftar['id_lowongan'],
                'name' => $pendaftar['name'],
                'gender' => $pendaftar['gender'],
                'dob' => $pendaftar['dob'],
                'address' => $pendaftar['address'],
                'no_telp' => $pendaftar['no_telp'],
                'university' => $pendaftar['university'],
                'major' => $pendaftar['major'],
                'ipk' => $pendaftar['ipk'],
                'status' => $pendaftar['status'],
                'path_cv' => $pendaftar['path_cv'],
                'created_at' => now()->subDays(rand(1, 10)),
                'updated_at' => now()->subDays(rand(1, 10)),
            ]);
        }
    }
}

